apiVersion: v1
kind: Pod
metadata: 
  name: fresco-nginx-pod
spec:
  containers:
    - name: fresco-nginx-container
      image: nginx
      env:
        - name: SERVER_URL_ENV
          valueFrom:
            configMapKeyRef:
              name: fresco-config
              key: SERVER_URL
      volumeMounts: 
        - name: pvc-claim
          mountPath:  "usr/share/nginx/html"
  volumes:
    - name: pvc-claim
      persistentVolumeClaim:
        claimName: fresco-pvc
