apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: emp-role
rules:
  - apiGroups: [""]
    resources: ["pods","deployments"]
    verbs: ["get","lists"]
    
--------------------------------------------------------

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""] # the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
