apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: emp-bind
subjects:
  - kind: user
    name: emp
    apiGroup: rbac.authorization.k8s.io/v1
roleRef:
  kind: Role
  name: emp-role
  apiGroup: rbac.authorization.k8s.io/v1
