# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   namespace: dev
#   name: emp-bind
# subjects:
#   - kind: User
#     name: emp
#     apiGroup: rbac.authorization.k8s.io
# roleRef:
#   kind: Role
#   name: emp-role
#   apiGroup: rbac.authorization.k8s.io

# ------------------------------------------------------

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: emp-bind
  namespace: dev
subjects:
- kind: User
  name: emp
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: emp-role
  apiGroup: rbac.authorization.k8s.io

#   Ref: https://github.com/HoussemDellai/rbac-kubernetes-minikube/blob/master/role-binding.yaml
