# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: dev
#   name: emp-role
# rules:
#   - apiGroups: [""]
#     resources: ["pods","deployments"]
#     verbs: ["get","lists"]
    
# --------------------------------------------------------

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev
  name: emp-role
rules:
- apiGroups: ["","apps"] # the core API group
  resources: ["pods","deployments"]
  verbs: ["get", "list"]
